language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn build

notifications:
  email: 
    recipients:
      - eormeno12@gmail.com
      - ernesto.ormeno@utec.edu.pe
    on_success: always
    on_failure: always

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-toke: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Project Deploy"
  on:
    branch: master